#ifndef OPENMW_MP_PACKETID_HPP
#define OPENMW_MP_PACKETID_HPP

namespace mwmp
{
    using PacketId = unsigned char;
}

enum : mwmp::PacketId
{
    ID_CONNECTED_PING = 0,
    ID_UNCONNECTED_PING = 1,
    ID_SND_RECEIPT_ACKED = 14,
    ID_SND_RECEIPT_LOSS = 15,
    ID_CONNECTION_REQUEST_ACCEPTED = 16,
    ID_CONNECTION_ATTEMPT_FAILED = 17,
    ID_ALREADY_CONNECTED = 18,
    ID_NEW_INCOMING_CONNECTION = 19,
    ID_NO_FREE_INCOMING_CONNECTIONS = 20,
    ID_DISCONNECTION_NOTIFICATION = 21,
    ID_CONNECTION_LOST = 22,
    ID_CONNECTION_BANNED = 23,
    ID_INVALID_PASSWORD = 24,
    ID_INCOMPATIBLE_PROTOCOL_VERSION = 25,
    ID_REMOTE_DISCONNECTION_NOTIFICATION = 31,
    ID_REMOTE_CONNECTION_LOST = 32,
    ID_REMOTE_NEW_INCOMING_CONNECTION = 33,
    ID_USER_PACKET_ENUM = 134
};

#endif
